import { useNavigate } from "react-router-dom";
import React, { useState, useEffect } from "react";
import {
  getReports,
  getReportById,
  addReport,
  updateReport,
  deleteReport,
} from "../../api/reportApi";
import Header from "../../components/Header";
import Sidebar from "../../components/Sidebar";
import "../../styles/layout.css";
import "../../styles/Dashboard.css";

function Reports() {

const [reportData, setReportData] = useState([]);

useEffect(() => {
  fetchReports();
}, []);

const fetchReports = async () => {
  try {
    const response = await getReports();
    setReportData(response.data);
  } catch (error) {
    console.error("Error fetching reports:", error);
  }
};

const [showForm, setShowForm] = React.useState(false);
const [viewReport, setViewReport] = React.useState(null);
const [isEditing, setIsEditing] = React.useState(false);

const [search, setSearch] = React.useState("");
const [reportFilter, setReportFilter] = React.useState("");
const [newReport, setNewReport] = React.useState({
  id: "",
  reportName: "",
  generatedBy: "",
  date: "",
  status: "Pending",
});

const handleGenerateReport = () => {
  setIsEditing(false);

  setNewReport({
    id: "",
    reportName: "",
    generatedBy: "",
    date: "",
    status: "Pending",
  });

  setShowForm(true);
};

const handleView = async (id) => {
  try {
    const response = await getReportById(id);
    setViewReport(response.data);
  } catch (error) {
    console.error(error);
  }
};


const handleEdit = async (id) => {
  console.log("Edit clicked:", id);

  try {
    const response = await getReportById(id);

    console.log(response.data);

    setNewReport(response.data);
    setIsEditing(true);
    setShowForm(true);
  } catch (error) {
    console.error(error);
  }
};

const handleDownload = (id) => {
  const report = reportData.find((r) => r.id === id);

  if (!report) return;

  const content = `
Report ID : ${report.id}
Report Name : ${report.reportName}
Generated By : ${report.generatedBy}
Date : ${report.date}
Status : ${report.status}
`;

  const blob = new Blob([content], { type: "text/plain" });

  const link = document.createElement("a");

  link.href = URL.createObjectURL(blob);

  link.download = `${report.id}.txt`;

  link.click();
};


const filteredReports = reportData.filter((report) => {

  const searchMatch =
    report.id.toLowerCase().includes(search.toLowerCase()) ||
    report.reportName.toLowerCase().includes(search.toLowerCase());

  const typeMatch =
    reportFilter === "" ||
    report.reportName === reportFilter;

  return searchMatch && typeMatch;
});

const handleSave = async () => {
  if (
    !newReport.id ||
    !newReport.reportName ||
    !newReport.generatedBy ||
    !newReport.date
  ) {
    alert("Please fill all fields");
    return;
  }

  try {
    await addReport(newReport);
    await fetchReports();

    setShowForm(false);

    setNewReport({
      id: "",
      reportName: "",
      generatedBy: "",
      date: "",
      status: "Pending",
    });

    alert("Report Generated Successfully!");
  } catch (error) {
    console.error(error);
  }
};





const handleUpdate = async () => {
  try {
    await updateReport(newReport.id, newReport);
    await fetchReports();
    

    setShowForm(false);
    setIsEditing(false);

    alert("Report Updated Successfully!");
  } catch (error) {
    console.error(error);
  }
};


const handleDelete = async (id) => {
  if (window.confirm("Delete this report?")) {
    try {
      await deleteReport(id);
      fetchReports();
    } catch (error) {
      console.error(error);
    }
  }
};


  return (
    <div className="layout">
      <Sidebar activePage="Reports" />

      <div className="main-content">
        <Header title="Reports" />

        <div className="page-content">

          <h1 className="page-title">Reports & Analytics</h1>


          <div className="dashboard-grid">

<div className="dashboard-card">
<h3>Total Reports</h3>
<h2>{reportData.length}</h2>
</div>

<div className="dashboard-card">
<h3>Completed</h3>
<h2>{reportData.filter(r=>r.status==="Completed").length}</h2>
</div>

<div className="dashboard-card">
<h3>Pending</h3>
<h2>{reportData.filter(r=>r.status==="Pending").length}</h2>
</div>

</div>

          <div className="employee-toolbar">

<input
className="search-box"
placeholder="Search Report..."
value={search}
onChange={(e)=>setSearch(e.target.value)}
/>

<select
className="filter-box"
value={reportFilter}
onChange={(e)=>setReportFilter(e.target.value)}
>
<option value="">All Reports</option>
<option>Attendance Report</option>
<option>Payroll Report</option>
<option>Leave Report</option>
<option>Employee Report</option>
</select>

<button
className="action-btn"
onClick={()=>{
setSearch("");
setReportFilter("");
}}
>
Reset
</button>

<button
className="add-btn"
onClick={handleGenerateReport}
>
Generate Report
</button>

          </div> 

          {showForm && (
<div className="popup-overlay">
<div className="popup-form">

<h2>
  {isEditing ? "Edit Report" : "Generate Report"}
</h2>

<input
type="text"
placeholder="Report ID"
value={newReport.id}
onChange={(e)=>setNewReport({...newReport,id:e.target.value})}
/>

<input
type="text"
placeholder="Report Name"
value={newReport.reportName}
onChange={(e)=>setNewReport({...newReport,reportName:e.target.value})}
/>

<input
type="text"
placeholder="Generated By"
value={newReport.generatedBy}
onChange={(e)=>setNewReport({...newReport,generatedBy:e.target.value})}
/>

<input
type="date"
value={newReport.date}
onChange={(e)=>setNewReport({...newReport,date:e.target.value})}
/>

<select
value={newReport.status}
onChange={(e)=>setNewReport({...newReport,status:e.target.value})}
>
<option>Pending</option>
<option>Completed</option>
</select>

<button
  className="add-btn"
  onClick={isEditing ? handleUpdate : handleSave}
>
  {isEditing ? "Update" : "Save"}
</button>

<button
className="delete-btn"
onClick={()=>{
  setShowForm(false);
  setIsEditing(false);

  setNewReport({
    id:"",
    reportName:"",
    generatedBy:"",
    date:"",
    status:"Pending",
  });
}}
>
Cancel
</button>

</div>
</div>
)}


{viewReport && (

<div className="popup-overlay">

<div className="popup-form">

<h2>Report Details</h2>

<p><strong>ID:</strong> {viewReport.id}</p>
<p><strong>Report:</strong> {viewReport.reportName}</p>
<p><strong>Generated By:</strong> {viewReport.generatedBy}</p>
<p><strong>Date:</strong> {viewReport.date}</p>
<p><strong>Status:</strong> {viewReport.status}</p>

<button
className="add-btn"
onClick={()=>setViewReport(null)}
>
Close
</button>

</div>

</div>

)}






          <div className="table-container">

            <table className="employee-table">

              <thead>
                <tr>
                  <th>Report ID</th>
                  <th>Report Name</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th>Status</th>
                  <th>Download</th>
                </tr>
              </thead>

<tbody>

{filteredReports.map((report)=>(

<tr key={report.id}>

<td>{report.id}</td>

<td>{report.reportName}</td>

<td>{report.generatedBy}</td>

<td>{report.date}</td>

<td>

<span
className={`status ${
report.status==="Completed"
? "active"
: "pending"
}`}
>
{report.status}
</span>

</td>

<td>

<button
className="action-btn view"
onClick={()=>handleView(report.id)}
>
View
</button>

<button
className="action-btn edit"
onClick={()=>handleDownload(report.id)}
>
Download
</button>

<button
  className="action-btn delete"
  onClick={() => handleDelete(report.id)}
>
  Delete
</button>


<button
  className="action-btn edit"
  onClick={() => handleEdit(report.id)}
>
  Edit
</button>


</td>

</tr>

))}

</tbody>

            </table>

          </div>

        </div>
      </div>
    </div>
  );
}

export default Reports;